### ISSUE TITLE
Errors when run gym_tvizdoom

### ISSUE THREAD

**Issue by Tie-1** [whluo/active_tracking_drl#3]
I followed install instructions from the [README]
After running 
`python train.py --num-workers=2 --env-id=TrackObjSmallMazeRandFlip-v2 --log-dir=save/to --max-global-steps=29999 --val-model-secs=30 --max-val-episodes=2`
some errors appeared:

> I tensorflow/core/common_runtime/simple_placer.cc:827] global/RNN/while/BasicLSTMCell/split/split_dim: (Const)/job:worker/replica:0/task:1/cpu:0
global/RNN/while/BasicLSTMCell/Linear/concat/concat_dim: (Const): /job:worker/replica:0/task:1/cpu:0
I tensorflow/core/common_runtime/simple_placer.cc:827] global/RNN/while/BasicLSTMCell/Linear/concat/concat_dim: (Const)/job:worker/replica:0/task:1/cpu:0
[2022-04-03 20:38:01,889] Called reset on <Unvectorize<VectorizeFilter[<class 'envs.DiagnosticsInfoI'>]<VizdoomRescale84x84x3<Vectorize<TimeLimit<TrackObjSmallMazeRandFlipV2Env instance>>>>>> before configuring. Configuring automatically with default arguments
[2022-04-03 20:38:01,910] Starting training at step=30175
[2022-04-03 20:38:01,923] reached 30175 steps. worker stopped.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/gym/utils/closer.py", line 67, in close
    closeable.close()
  File "/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/gym/core.py", line 188, in close
    self.render(close=True)
  File "/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/gym/core.py", line 165, in render
    return self._render(close=close)
  File "/home/dell/hzt/tracker/gym-tvizdoom/gym_tvizdoom/envs/track_obj_small_maze_rand_flip_v2_env.py", line 122, in _render
    return self._flip_screen(ret)
  File "/home/dell/hzt/tracker/gym-tvizdoom/gym_tvizdoom/envs/track_obj_small_maze_rand_flip_v2_env.py", line 103, in _flip_screen
    return np.fliplr(screen)
  File "/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/numpy/lib/twodim_base.py", line 81, in fliplr
    raise ValueError("Input must be >= 2-d.")
ValueError: Input must be >= 2-d.
terminate called without an active exception
Aborted (core dumped)

Ubuntu 20.04
Python 3.7
tensorflow 0.12
I spent too much time on it, but still not fix it out, can you give me some advice? Thank you!

**Comment by whluo** [comment]
> I followed install instructions from the [README] After running `python train.py --num-workers=2 --env-id=TrackObjSmallMazeRandFlip-v2 --log-dir=save/to --max-global-steps=29999 --val-model-secs=30 --max-val-episodes=2` some errors appeared:
> 
> > I tensorflow/core/common_runtime/simple_placer.cc:827] global/RNN/while/BasicLSTMCell/split/split_dim: (Const)/job:worker/replica:0/task:1/cpu:0
> > global/RNN/while/BasicLSTMCell/Linear/concat/concat_dim: (Const): /job:worker/replica:0/task:1/cpu:0
> > I tensorflow/core/common_runtime/simple_placer.cc:827] global/RNN/while/BasicLSTMCell/Linear/concat/concat_dim: (Const)/job:worker/replica:0/task:1/cpu:0
> > [2022-04-03 20:38:01,889] Called reset on <Unvectorize<VectorizeFilter[<class 'envs.DiagnosticsInfoI'>]<VizdoomRescale84x84x3<Vectorize<TimeLimit>>>>> before configuring. Configuring automatically with default arguments
> > [2022-04-03 20:38:01,910] Starting training at step=30175
> > [2022-04-03 20:38:01,923] reached 30175 steps. worker stopped.
> > Error in atexit._run_exitfuncs:
> > Traceback (most recent call last):
> > File "/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/gym/utils/closer.py", line 67, in close
> > closeable.close()
> > File "/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/gym/core.py", line 188, in close
> > self.render(close=True)
> > File "/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/gym/core.py", line 165, in render
> > return self._render(close=close)
> > File "/home/dell/hzt/tracker/gym-tvizdoom/gym_tvizdoom/envs/track_obj_small_maze_rand_flip_v2_env.py", line 122, in _render
> > return self._flip_screen(ret)
> > File "/home/dell/hzt/tracker/gym-tvizdoom/gym_tvizdoom/envs/track_obj_small_maze_rand_flip_v2_env.py", line 103, in _flip_screen
> > return np.fliplr(screen)
> > File "/home/dell/anaconda3/envs/tracker/lib/python3.5/site-packages/numpy/lib/twodim_base.py", line 81, in fliplr
> > raise ValueError("Input must be >= 2-d.")
> > ValueError: Input must be >= 2-d.
> > terminate called without an active exception
> > Aborted (core dumped)
> 
> Ubuntu 20.04 Python 3.7 tensorflow 0.12 I spent too much time on it, but still not fix it out, can you give me some advice? Thank you!

Thanks for your interest. Have you strictly followed the instructions in this repo to set up the gym-tvizdoom?

https://bitbucket.org/pengsun000/gym-tvizdoom/src/master/
